### ISSUE TITLE
interesting error spotted

### ISSUE THREAD

**Issue by Dieterbe** [mjibson/mog#27]
```
2015/09/21 11:07:57 next
2015/09/21 11:07:57 stop
2015/09/21 11:07:57 play
2015/09/21 11:07:57 unknown id: file
/home/dieter/music-sdcard
/home/dieter/music-sdcard/Oceans of Sadness/ Send in the Clowns/05 - Conflict �?? Error �?? Disillusion �?? Denial.mp3

goroutine 5 [running]:
github.com/mjibson/mog/server.printErr(0x7f3f7db3d028, 0xc825fc20e0)
	/home/dieter/go/src/github.com/mjibson/mog/server/server.go:38 +0x134
github.com/mjibson/mog/server.(*Server).commands.func3(0x7f3f7db3d028, 0xc825fc20e0)
	/home/dieter/go/src/github.com/mjibson/mog/server/control.go:39 +0x46
github.com/mjibson/mog/server.(*Server).commands.func11()
	/home/dieter/go/src/github.com/mjibson/mog/server/control.go:168 +0x489
github.com/mjibson/mog/server.(*Server).commands.func14()
	/home/dieter/go/src/github.com/mjibson/mog/server/control.go:235 +0x105
github.com/mjibson/mog/server.(*Server).commands.func8()
	/home/dieter/go/src/github.com/mjibson/mog/server/control.go:110 +0xfb
github.com/mjibson/mog/server.(*Server).commands(0xc8200d61e0)
	/home/dieter/go/src/github.com/mjibson/mog/server/control.go:408 +0x1329
created by github.com/mjibson/mog/server.New
	/home/dieter/go/src/github.com/mjibson/mog/server/server.go:188 +0x5d0

2015/09/21 11:07:57 server.controlCmd
```

**Comment by mjibson** [comment]
This looks like a weird filename error. What OS? On linux I made a filename with the unicode snowman, spaces, and other things, and it worked correctly.

**Comment by Dieterbe** [comment]
arch linux. it's possible that the chars are not actually unicode, maybe the filename got corrupted? (still mog shouldn't suffer this much)

**Comment by mjibson** [comment]
Can you post the filename here?

**Comment by Dieterbe** [comment]
well my shell has issues rendering the chars, but this should do it:
```
~/m/O/ Send in the Clowns ❯❯❯ ls -alh 05\ -\ Conflict\ $'\342'\?\?\ Error\ $'\342'\?\?\ Disillusion\ $'\342'\?\?\ Denial.mp3
-rwxr-xr-x 1 dieter dieter 1.8M Oct 27  2005 05 - Conflict ??? Error ??? Disillusion ??? Denial.mp3
```
